let h = `rock,paper,scissor`;           // pre-define the string with weapons


//random turn generated by computer.

let computerPlay = () => {

    computerSelection = "";

    let compChoice = Math.floor(Math.random() * 3);
    if (compChoice == 1) {
        computerSelection = `rock`;
        //  console.log("rock");
    }
    else if (compChoice == 2) {
        computerSelection = `paper`;
        //  console.log("paper");
    }
    else {
        computerSelection = `scissor`;
        //  console.log("Scissor");
    }
}


//INput by user

let userPlay = () => {

    playerSelection = ``;

    playerSelection = prompt("Your Turn ");
    playerSelection = playerSelection.toLowerCase();
}


//Real Game

let playRound = (c, p) => {

    computerPlay();
    c = computerSelection;

    userPlay();
    p = playerSelection;

    win = true;

    if (computerSelection === "rock" && playerSelection === "paper") {
        console.log("You win this round");
        win;
    }
    else if (computerSelection === "rock" && playerSelection === "rock") {
        console.log("Tie");
    }
    else if (computerSelection === "rock" && playerSelection === "scissor") {
        console.log("Computer win this round");
        win = false;
    }
    else if (computerSelection === "paper" && playerSelection === "rock") {
        console.log("Computer win this round");
        win = false;
    }
    else if (computerSelection === "paper" && playerSelection === "paper") {
        console.log("Tie");
    }
    else if (computerSelection === "paper" && playerSelection === "scissor") {
        console.log("You win this round");
    }
    else if (computerSelection === "scissor" && playerSelection === "rock") {
        console.log("You win this round");
    } else if (computerSelection === "scissor" && playerSelection === "paper") {
        console.log("Computer win this round");
        win = false;
    } else if (computerSelection === "scissor" && playerSelection === "scissor") {
        console.log("Tie");
    }




}



// 5 Rounds to be played to announce winner. 

let Game = () => {

    let i = 0;
    let computerWin = 0;
    let playerWin = 0;

    while (i < 5) {
        playRound();

        if (win === true) {
            playerWin++;
        }
        else if (win === false) {
            computerWin++;
        }
        i++;
    }

    if (playerWin > computerWin) {
        console.log("Final Result => Congratulations You win :) ");
    }
    else if (playerWin == computerWin) {
        console.log("Final Result => Draw :|  ");
    }
    else {
        console.log("Final Result => Alas! Computer Wins - you loose :( ");
    }

}




//for desktop on Screen play 
let gameScreen = (c, p) => {

    computerPlay();
    c = computerSelection;

    userPlay();
    p = playerSelection;

    let res = document.getElementById("result");

    if (computerSelection === "rock" && playerSelection === "paper") {
        res.innerHTML = "Computer Wins , You Loose .";
    }
    else if (computerSelection === "rock" && playerSelection === "rock") {
        res.innerHTML = " Tie ";
    }
    else if (computerSelection === "rock" && playerSelection === "scissor") {
        res.innerHTML = "Computer Wins , You Loose .";
    }
    else if (computerSelection === "paper" && playerSelection === "rock") {
        res.innerHTML = "Computer Wins , You Loose .";
    }
    else if (computerSelection === "paper" && playerSelection === "paper") {
        res.innerHTML = " Tie ";
    }
    else if (computerSelection === "paper" && playerSelection === "scissor") {
        res.innerHTML = " You Win .";
    }
    else if (computerSelection === "scissor" && playerSelection === "rock") {
        res.innerHTML = " You Win .";
    }
    else if (computerSelection === "scissor" && playerSelection === "paper") {
        res.innerHTML = "Computer Wins , You Loose .";
    }
    else if (computerSelection === "scissor" && playerSelection === "scissor") {
        res.innerHTML = " Tie ";
    }


}